language: node_js
node_js:
  - "10.9.0"

branches:
  only:
    - master

before_script:
  - npm install --dev
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  # - npm run lint
  - npm run build-prod

after_success:
  - firebase deploy --project tv-show-bookmark --only hosting --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
